//
// Created by Mew on 2/7/2023.
//
#include <stdbool.h>
#include "Constants.h"

int board[20 + 1][4] = {
        {BOARD_EMPTY_CELL, CHAR_USER, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL},
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        { BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL, BOARD_EMPTY_CELL },
        {7, 15, DIFFICULTY_EASY, false} // StatusRow
};

