//
// Created by SMhd3 on 2/7/2023.
//

#ifndef SPACEINVADERS_TYPES_H
#define SPACEINVADERS_TYPES_H

typedef enum page {
  SCREEN_HOME,
  SCREEN_ABOUT,
  SCREEN_INPUT_NAME,
  SCREEN_SET_LEVEL,
  SCREEN_GAME
} ScreenType;

#endif //SPACEINVADERS_TYPES_H
