//
// Created by SMhd3 on 2/7/2023.
//

#ifndef SPACEINVADERS_TYPES_H
#define SPACEINVADERS_TYPES_H

typedef enum page {
  SCREEN_HOME,
  SCREEN_MENU,
  SCREEN_ABOUT,
  SCREEN_INPUT_NAME,
  SCREEN_SET_DIFFICULTY,
  SCREEN_GAME,
  SCREEN_END_GAME_WIN,
  SCREEN_END_GAME_LOST
} ScreenType;

#endif //SPACEINVADERS_TYPES_H
